sudo: required

services:
  - docker

script:
  pwd
  docker run -v /home/travis/build/Fazendaaa/project-euler/src/r/:/toBeTested -t fazenda/r-testing /bin/sh -c "cd toBeTested && R -e 'devtools::test()'"

after_success:
  R -e 'covr::codecov()'
  R -e 'covr::coveralls()'
